env:
  es2017: true
  browser: true
  commonjs: true

extends: ['htmlacademy/es6', 'plugin:react/recomended']

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react']

setting:
  react:
    version: '16'
